### ISSUE TITLE
Where's SDL_RWops?

### ISSUE THREAD

**Issue by ghost** [ohai/ruby-sdl2#23]
I want to read a some pixel data from memory instead of from a file, but there doesn't seem to be an wrapper for SDL_RWops. Was there a technical limitation that cause this?

**Comment by ohai** [comment]
Hello. That is because SDL_RWops deeply depends on the C language. Careless usage of SDL_RWopds from Ruby will make SEGV easily.

If your data is "raw" pixel data,  [SDL2::Surface.from_string](http://ohai.github.io/ruby-sdl2/doc-en/SDL2/Surface.html#from_string-class_method) method is available. 

If your data is PNG or something, it is impossible to use the data now. If you have a use-case of loading such data from Ruby's string, I will add `SDL2::Surface.load_from_string` method.

**Comment by ghost** [comment]
Okay, I get it. It's fine I can do without it.
